### ISSUE TITLE
Мій звіт про результати коміта

### ISSUE THREAD

**Issue by oleksandr-lisnychenko** [oleksandr-lisnychenko/MTDIP-Lisnychenko-MainProject.#1]
// Встановити відповідальність (Assignee) за issues користувача
Smoktii.igov@gmail.com (це буде можливо тільки після підтвердження
авторизації Smoktii.igov@gmail.com)

![snipaste_2018-11-25_11-44-40](https://user-images.githubusercontent.com/15153406/48978124-50c79400-f0af-11e8-8351-a131b6329ae9.png)
![snipaste_2018-11-25_12-02-37](https://user-images.githubusercontent.com/15153406/48978125-50c79400-f0af-11e8-9ea2-4927536d83ea.png)
![snipaste_2018-11-25_12-09-01](https://user-images.githubusercontent.com/15153406/48978126-50c79400-f0af-11e8-9277-4799ed944906.png)
![snipaste_2018-11-25_12-11-21](https://user-images.githubusercontent.com/15153406/48978127-50c79400-f0af-11e8-8eb8-d1ac740af0c6.png)

**Comment by oleksandr-lisnychenko** [comment]
![snipaste_2018-11-26_20-28-46](https://user-images.githubusercontent.com/15153406/49034513-ddab4400-f1ba-11e8-9b4e-b2fbc9043d46.png)

**Comment by oleksandr-lisnychenko** [comment]
push to master
![snipaste_2018-11-26_20-39-37](https://user-images.githubusercontent.com/15153406/49034807-9ffaeb00-f1bb-11e8-8b1f-03f8024c81cc.png)

**Comment by smoktii-igov** [comment]
Close
